apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chmod -R 777 /usr/share/nginx/html"]
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html  # Ruta donde Nginx sirve los archivos HTML
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html  # Ruta donde Nginx sirve los archivos HTML
      volumes:
      - name: html-volume
        gitRepo:
          repository: https://github.com/btovc/mi-app-albert.git  # URL de tu repositorio
          revision: main  # La rama que quieras usar
          directory: html  # Directorio en tu repositorio que contiene index.html


