apiVersion: apps/v1
kind: Deployment
metadata:
  name: asir-app-albert
  labels:
    app: nginx
    version: "v1.0.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "250m"  # Solicitar solo 0.25 CPUs
            memory: "50Mi"  # Solicitar 50Mi de memoria
          limits:
            cpu: "500m"  # Limitar a un máximo de 0.5 CPUs
            memory: "100Mi"  # Limitar a 100Mi de memoria
        volumeMounts:
        - name: nginx-html
          mountPath: /usr/share/nginx/html  # Ruta estándar donde Nginx espera los archivos
      volumes:
      - name: nginx-html
        configMap:
          name: nginx-html  # ConfigMap que contiene el archivo index.html




