apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
    version: "v1.0.1"
    changelog: |
      - Mejoras en el rendimiento de la p치gina de inicio.
      - Se corrigi칩 un error en la carga de im치genes.
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-html
          mountPath: /usr/share/nginx/html  # Ruta est치ndar donde Nginx espera los archivos
      volumes:
      - name: nginx-html
        configMap:
          name: nginx-html  # ConfigMap que contiene el archivo index.html



