apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
  namespace: default  # O el namespace donde deseas desplegarlo
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Proyecto de Fin de Curso ARGOCD - ASIR</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                margin: 0;
                padding: 0;
                background-color: #f4f4f4;
            }
            header {
                background: #ff6600;
                color: white;
                padding: 10px 0;
                text-align: center;
            }
            h1 {
                margin: 0;
                font-size: 2.5em;
            }
            h2 {
                color: white;
            }
            .container {
                max-width: 800px;
                margin: 20px auto;
                padding: 20px;
                background: white;
                border-radius: 8px;
                box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            }
            .content {
                margin: 20px 0;
            }
            footer {
                text-align: center;
                padding: 10px 0;
                background: #ff6600;
                color: white;
                position: relative;
                bottom: 0;
                width: 100%;
            }
            a {
                color: #007BFF;
                text-decoration: none;
            }
            a:hover {
                text-decoration: underline;
            }
        </style>
    </head>
    <body>

    <header>
        <h1>ARGOCD y Github</h1>
        <h2>Demostración de ARGOCD</h2>
    </header>

    <div class="container">
        <div class="content">
            <h3>Bienvenido a mi proyecto</h3>
            <p>Esta página ha sido desplegada en un clúster de <strong> Kubernetes </strong> utilizando <strong> ArgoCD </strong> y está alojada en <strong> GitHub </strong>.</p>
            <p>Visita el repositorio en GitHub para acceder a la <a href="https://github.com/btovc/mi-app-albert/" target="_blank">documentación completa y la descarga de la aplicación</a>.</p>
            <p>Argo es un conjunto de herramientas open-source diseñadas para mejorar la entrega continua y la automatización de procesos en Kubernetes. Originado por Applatix (ahora parte de Intuit),
            Argo ha evolucionado para ser una solución robusta y versátil, respaldada por la Cloud Native Computing </p>
     <h3>Ventajas de usar ArgoCD</h3>

        <li><strong>Automatización y simplificación:</strong> simplifica y automatiza los despliegues, reduciendo errores y tiempo de implementación.</li>
        <li><strong>Eficiencia operacional:</strong> mejora la eficiencia operativa al automatizar tareas repetitivas y complejas.</li>
        <li><strong>Flexibilidad y adaptabilidad:</strong> se adapta a diversas necesidades, permitiendo configuraciones personalizadas.</li>
        <li><strong>Facilita GitOps:</strong> promueve las prácticas de GitOps, mejorando el control y seguimiento de configuraciones y despliegues.</li>
   
        </div>
        <p>Para más información sobre ArgoCD, visita su <a href="https://argo-cd.readthedocs.io/" target="_blank">documentación oficial</a>.</p>
    </div>

    <footer>
        <p>&copy; 2024 Proyecto ASIR - Todos los derechos reservados. Alberto Vázquez</p>
    </footer>

    </body>
    </html>

