apiVersion: v1
kind: Service
metadata:
  name: albert-asir-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80        # Puerto interno del clúster
      targetPort: 80  # Puerto del contenedor
      nodePort: 30084 # Puerto externo del nodo (opcional)
  type: NodePort      # Cambiamos el tipo de servicio
