name: Deploy to GitHub Pages

on:
  push:
    branches:
      - 'main/root'  # Configura para la rama 'main/root'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: 'main/root'  # Asegúrate de hacer checkout en la rama correcta

      - name: Set up Node.js (o tu entorno necesario)
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Cambia esto según el entorno que estés usando

      - name: Build project (si necesitas compilar algo)
        run: |
          # Aquí se colocan los pasos para construir tu proyecto
          mkdir -p build
          echo "Hello, World!" > build/index.html  # Solo un ejemplo

      - name: Upload artifact (si es necesario)
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: build  # Ajusta esto al directorio que contiene tus archivos de despliegue

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages  # Asegúrate de que el nombre coincida con el nombre del artefacto
















