name: Incrementar versión automáticamente

on:
  push:
    branches:
      - main

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Leer y actualizar la versión
        run: |
          VERSION=$(cat VERSION)
          echo "Versión actual: $VERSION"
          NEW_VERSION=$(echo $VERSION | awk -F. '{print $1"."$2"."$3+1}')
          echo "$NEW_VERSION" > VERSION
          echo "Nueva versión: $NEW_VERSION"

      - name: Commit y Push de la nueva versión
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}
          git add VERSION
          git commit -m "Actualización de la versión a $(cat VERSION)"
          git push origin main











