name: Update Version

on:
  push:
    paths:
      - 'VERSION'

jobs:
  increment_version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Increment Version
      run: |
        # Leer la versión actual
        CURRENT_VERSION=$(cat VERSION)
        echo "Versión actual: $CURRENT_VERSION"
        
        # Descomponer la versión en partes (mayor, menor, parche)
        IFS='.' read -r -a VERSION_PARTS <<< "$CURRENT_VERSION"
        PATCH=${VERSION_PARTS[2]}
        
        # Incrementar el número de parche
        PATCH=$((PATCH + 1))
        
        # Crear la nueva versión
        NEW_VERSION="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.$PATCH"
        echo "Nueva versión: $NEW_VERSION"
        
        # Guardar la nueva versión en el archivo VERSION
        echo $NEW_VERSION > VERSION
        
    - name: Commit and Push version change
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add VERSION
        git commit -m "Increment version to $NEW_VERSION"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}















