name: Actualizar versión y changelog

on:
  push:
    paths:
      - 'VERSION'
      - 'manifests/**'
      - 'configmaps.yaml'
      - 'CHANGELOG.md'

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Chequear el código
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      # Paso 2: Leer la versión desde el archivo VERSION
      - name: Leer versión desde el archivo VERSION
        id: version
        run: |
          VERSION=$(cat VERSION)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Paso 3: Incrementar la versión (por ejemplo, incrementar el patch)
      - name: Incrementar versión
        id: increment
        run: |
          IFS='.' read -r major minor patch <<< "${{ env.VERSION }}"
          patch=$((patch + 1))
          new_version="${major}.${minor}.${patch}"
          echo "Nueva versión: $new_version"
          echo "$new_version" > VERSION
          echo "VERSION=$new_version" >> $GITHUB_ENV

      # Paso 4: Generar el changelog
      - name: Generar changelog
        id: changelog
        run: |
          echo "Actualización a la versión ${{ env.VERSION }}: Cambios en configuración y mejoras" > CHANGELOG.md
          echo "Changelog generado: $(cat CHANGELOG.md)"

      # Paso 5: Hacer commit y push de los cambios
      - name: Commit y Push de cambios
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add VERSION CHANGELOG.md
          git commit -m "Actualización a la versión ${{ env.VERSION }} con cambios en configuraciones"
          git push https://github.com/${{ github.repository }} HEAD:${{ github.ref }} --token ${{ secrets.GITHUB_TOKEN }}







